const technology = [
  "Confetti.js",
  "Modules",
  "CORS",
  "DOM",
  "localStorage",
  "CSS Animations",
  "Text to Speech",
  "Date",
  "Array Methods",
  "MathMethods",
  "DOM Basics",
  "Forms",
  "Async/Await",
  "Fetch",
  "Scroll Event Listener",
  "AOS.js",
  "Advanced HTML Canvas",
  "SetInterval",
  "Template",
];

const myProjects = [
  "Spock Rock Game",
  "Quote Generator",
  "Picture-in-Picture",
  "Bookmarks App",
  "NASA APOD",
  "Animated Navigation",
  "Infinite Scroll",
  "Countdown App",
  "Music Player",
  "Calculator",
  "Splash Page",
  "Light/Dark Mode",
  "Form Validation",
  "Joke Teller",
  "Video Player",
  "MS Paint Clone",
  "Pong Clone",
  "Math Sprint Game",
  "Animated Template",
  "Drag and Drop",
];
